# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6b1458f8731895825390be0dab320f272c264be8577273f00ea7c0da2d738e83158cd76e1b7299ccb398be0bb712bf0fa6e8c663ed1dbc59e3f8fdb0adcfebd

test:
  secret_key_base: 132316006be45e54ddea651efa91794633991ed54c6d912af36408a20c48c7d935a67cafd5bb6d9df70da13988afd50d70f555dc12cd48853f500e49d1db87d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
